### ISSUE TITLE
broken region information: all are set to unknown

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_graphql#149]
zos fetches the information from geoip service https://geoip.grid.tf

![image](https://github.com/threefoldtech/tfchain_graphql/assets/64129/0d4d1346-70af-4f31-b830-6ff5d2210b58)

![image](https://github.com/threefoldtech/tfchain_graphql/assets/64129/73171b95-4c2d-4e3e-8a0d-fca64612a2c2)

![image](https://github.com/threefoldtech/tfchain_graphql/assets/64129/3ef52fef-8e0b-4505-a36f-47114c8ac1bc)

processor code 
https://github.com/threefoldtech/tfchain_graphql/blob/da00000dd87ceca477991fbab9c0934aebd1b3f5/scripts/init-countries.js#L63
![image](https://github.com/threefoldtech/tfchain_graphql/assets/64129/4cdbcd43-f7e6-40da-b53f-7ea66fc51807)

so everything seems to be incheck, but graphql says otherwise

![image](https://github.com/threefoldtech/tfchain_graphql/assets/64129/3fbcfc75-d98b-4b1f-b68f-30f74196329b)

all of the records don't have the proper continent

**Comment by sameh-farouk** [comment]
This because `init-countries.js` gets countries from https://restcountries.com/v2/all and maps `continent` value to `region` and `region` value to `subregion` on our db. since the data served over this API have no `continent` filed at all. all regions on our db are set to default value "unknown region".

The mapping in `init-countries.js` should be corrected to:
- `region` -> `region` 
- `subregion` -> `subregion`

**Comment by sameh-farouk** [comment]
Update: Fix merged

![Screenshot from 2024-01-16 14-58-11](https://github.com/threefoldtech/tfchain_graphql/assets/42457449/67e0ea3b-f2aa-43e9-a67f-802acb4d30e6)

**Comment by sameh-farouk** [comment]
**Verified on devnet**

![Screenshot_20240128_173618](https://github.com/threefoldtech/tfchain_graphql/assets/42457449/036f2981-ca8c-443f-90a6-ed5a1d8f9490)
