### ISSUE TITLE
Added public ips on a farm are not always synced with the chain

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfchain_graphql#157]
env: devnet

farm: 52
![image](https://github.com/threefoldtech/tfchain_graphql/assets/41957921/51e9f35c-8f0f-41ed-8043-fd282308bde0)

![image](https://github.com/threefoldtech/tfchain_graphql/assets/41957921/d39d57e5-5ee8-490d-8957-5b13f38c07a8)

also, farm 4432 has the same issue

**Comment by sameh-farouk** [comment]
Update:
Still trying to figure out what is causing this.
- Did a code review.
- Checked if we are missing a Farm type change.
- Review previous changes done to farm type on the chain.

What I have found so far is that during an old tfchain migration, a state cleaning was performed to remove some bad IPs from the chain. This might have resulted in having more IPs than what we currently have in the chain. However, the OP mentioned that there are fewer IPs in the Graphql, indicating that there might be a different issue at play.

**Comment by Omarabdul3ziz** [comment]
i think we maybe have also a problem with deleting, some farms has ips on the database but not on the chain, what i noticed is farms 138, 33, 14
![image](https://github.com/threefoldtech/tfchain_graphql/assets/32527347/9040e0aa-6aa7-4b88-a2bf-075045ad88d4)
![image](https://github.com/threefoldtech/tfchain_graphql/assets/32527347/63268cc5-216f-4717-9a78-779184caa870)

**Comment by sameh-farouk** [comment]
@Omarabdul3ziz yes, that what i was saying in my previous comment. There is two issues in play here, the one you described is due to previous chain migration where we removed invalid IPs info from chain State without propagating this to our processor via tracked events. a gateway always have to be on the same subnet as the IP address. In your case, these IPs shows in graphql and not exists in chain due to being invalid.
A graphql migration should follow to remove these ips from graphql as well.

**Comment by sameh-farouk** [comment]
Update:
Farm 52 was created in block 1313143 with an empty set of IPs
it was updated a handful of times in different extrinsic since then, but this one is the most interesting
 
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftfchain.dev.grid.tf%2Fws#/extrinsics/decode/0x1908840060e6768d0f49b892e5d9e7f8247320687c28c2651c37e168c4a244c649ebe11c014e861a913967e5a97bffeadd0c7a8c834fe2cdc7ed8331079a991b0401c129651108390a6f00d97f2ef69ba9b30e88540ce3b03d53e1eacccf7bc171c78522892502c9440003024019053400000028312e312e312e352f32341c312e312e312e3019053400000028312e312e312e362f32341c312e312e312e3019053400000028312e312e312e372f32341c312e312e312e3019053400000028312e312e312e382f32341c312e312e312e3019053400000028312e312e312e392f32341c312e312e312e301905340000002c312e312e312e31302f32341c312e312e312e301905340000002c312e312e312e31312f32341c312e312e312e301905340000002c312e312e312e31322f32341c312e312e312e301905340000002c312e312e312e31332f32341c312e312e312e301905340000002c312e312e312e31342f32341c312e312e312e301905340000002c312e312e312e31352f32341c312e312e312e301905340000002c312e312e312e31362f32341c312e312e312e301905340000002c312e312e312e31372f32341c312e312e312e301905340000002c312e312e312e31382f32341c312e312e312e301905340000002c312e312e312e31392f32341c312e312e312e301905340000002c312e312e312e32302f32341c312e312e312e30

The same farm was updated about 15 times in the same batch extrinsic with different IP addresses each time.

The processor received all farm updated events. Because they were propagated from the same externsic and included in the same block, it processes the events in an undefined order resulting in an outdated set of ips to persist in processor db.

**Comment by sameh-farouk** [comment]
When dealing with events, it is important to process them based on their index within the block.

**Comment by sameh-farouk** [comment]
Update:
I wasn't able to reproduce the issue. I tried adding an IP range from the dashboard, and it seems that events from batch call are being processed with respect to the event index in the block, just as expected.

It would be very helpful if you could reproduce the issue and share the steps with us.

For now, what i can do a migration to remove the invalid IPs from GraphQL.

**Comment by AhmedHanafy725** [comment]
I tried it again adding 5 ips with batch call and nothing is showing in graphql ![image](https://github.com/threefoldtech/tfchain_graphql/assets/41957921/6d9b57cc-b33c-4f8a-855b-faa88f7b64f6)

while they are added on the chain
![image](https://github.com/threefoldtech/tfchain_graphql/assets/41957921/7ba882fb-b899-46f5-9f49-f0e266df20a7)

**Comment by sameh-farouk** [comment]
@AhmedHanafy725  Which network?

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 Which network?

devnet

**Comment by sameh-farouk** [comment]
Now it's clear what caused these synchronization issues.
IPs registered on the chain but not indexed by the processor are explained here [here](https://github.com/threefoldtech/tfchain_graphql/issues/157#issuecomment-2108192005).

IPs indexed by the processor but not exists on the chain are explained here [here](https://github.com/threefoldtech/tfchain_graphql/issues/157#issuecomment-2021848765).

**Comment by sameh-farouk** [comment]
Update: 
after dicuss this with @xmonader and @AhmedHanafy725 I suggested a solution  [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2726)

**Comment by sameh-farouk** [comment]
Update: a PR that handling this case https://github.com/threefoldtech/tfchain_graphql/issues/157#issuecomment-2021848765 is ready fore review
