### ISSUE TITLE
[Mainnet] graphql show power state as null for most of GE nodes

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/tfchain_graphql#196]
- for farm 77 "one of GE farms"
![Screenshot from 2024-11-26 16-59-45](https://github.com/user-attachments/assets/9eabc2a5-5093-46c3-a61e-f7f0539177a5)

- same query works for farm 1 "freefarm" 
![Screenshot from 2024-11-26 17-02-38](https://github.com/user-attachments/assets/cd6b24d0-9cda-421e-a2ba-d0379071e7ca)

**Comment by sameh-farouk** [comment]
This means no `PowerTargetChanged` or `PowerStateChanged` events are emitted for these nodes from TFChain. Since this farm doesn’t have a farmer-bot set up, this behavior is expected.

In our chain, we have two power-related events:

* `PowerTargetChanged`: Triggered when a farmer (or a farmer-bot acting on their behalf) executes the `change_power_target` runtime call.
* `PowerStateChanged`: Triggered when a node executes the `change_power_state` runtime call after adjusting its power state.

Here’s a brief explanation of the standby flow:

1. A farmer-bot calls `change_power_target` on-chain, prompting the chain to emit a `PowerTargetChanged` event.
2. The node receives this signal and responds by calling `change_power_state` on-chain before adjusting its low-power state, which then results in the chain emitting a `PowerStateChanged` event.

Without a farmer-bot managing the farm, I don't expect to see these events being emitted.

I believe @rawdaGastan or @xmonader might be able to confirm this based on their familiarity with the farmer-bot or Zos.

@hossnys, feel free to let me know if there’s anything else I can assist with regarding this issue.

**Comment by hossnys** [comment]
Thanks Sameh , that makes things more clear , as that Farm is not managed by Farmerbot so this seems to be normal .
