### ISSUE TITLE
Investigate FireSquid

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#43]
New version of subsquid, can index much faster. Might be very useful.

Use firesquid as indexer and align processor to be compatible.

Pros:

- 5x less storage
- atleast 10x sync speed

Cons:

- need to rewrite entire codebase

**Comment by despiegk** [comment]
I guess its now done, shouldn't there have been a story which got accepted by stakeholders?
also why didn't we get more feedback here?

**Comment by coesensbert** [comment]
The new firesquid + cockroach db is currently temporary exposed for devnet at https://graphql.dev.grid.tf/graphql
I did not experience or see others have issues since then, so we could be good to permanently set it as the graphql backend for devnet. https://github.com/threefoldtech/home/issues/1381

Qa, test and mainnet also have this ready (but not exposed yet). We have an firesquid indexer and processor synced and ready to switch once this would be required. But I'm not sure we should proceed since this was not defined for 3.8.1 @xmonader ?

Tell us when, and we can expose for QA-net (and others) so some test could be ran against it.

**Comment by despiegk** [comment]
how long does it take to now sync from scratch on mainnet?

**Comment by DylanVerstraete** [comment]
If you have some decent hardware you can sync 400-500 blocks per seconds, mainnet has around 5.6 mil blocks so it would take you around 3 - 4 hours. This compared to the previous version which synced only 10-50 blocks per seconds.

**Comment by despiegk** [comment]
wow thats a huge improvement
